[package]
name = "kog"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"
description = "A cross-platform, format-comprehensive local music player"
repository = "https://github.com/benwbooth/Kog"

[dependencies]
cxx = "1.0.176"
cxx-qt = "0.10.0"
cxx-qt-lib = { version = "0.10.0", features = ["full"] }

[build-dependencies]
cxx-qt-build = { version = "0.10.0", features = ["link_qt_object_files"] }
