// Generated reconstruction order from pinned ares/sfc/sfc.cpp.
inline void resetSnsfMachine() {
using namespace ares::SuperFamicom;
(void)ares::SuperFamicom::system; // initialize this worker before reconstructing instances
std::destroy_at(&ares::SuperFamicom::sufamiturboSlotB);
std::destroy_at(&ares::SuperFamicom::sufamiturboSlotA);
std::destroy_at(&ares::SuperFamicom::bsmemorySlot);
std::destroy_at(&ares::SuperFamicom::expansionPort);
std::destroy_at(&ares::SuperFamicom::superfx);
std::destroy_at(&ares::SuperFamicom::spc7110);
std::destroy_at(&ares::SuperFamicom::sharprtc);
std::destroy_at(&ares::SuperFamicom::sdd1);
std::destroy_at(&ares::SuperFamicom::sa1);
std::destroy_at(&ares::SuperFamicom::obc1);
std::destroy_at(&ares::SuperFamicom::necdsp);
std::destroy_at(&ares::SuperFamicom::msu1);
std::destroy_at(&ares::SuperFamicom::mcc);
std::destroy_at(&ares::SuperFamicom::icd);
std::destroy_at(&ares::SuperFamicom::hitachidsp);
std::destroy_at(&ares::SuperFamicom::epsonrtc);
std::destroy_at(&ares::SuperFamicom::dip);
std::destroy_at(&ares::SuperFamicom::competition);
std::destroy_at(&ares::SuperFamicom::armdsp);
std::destroy_at(&ares::SuperFamicom::ppuPerformanceImpl);
std::destroy_at(&ares::SuperFamicom::ppuImpl);
std::destroy_at(&ares::SuperFamicom::ppu);
std::destroy_at(&ares::SuperFamicom::dsp);
std::destroy_at(&ares::SuperFamicom::smp);
std::destroy_at(&ares::SuperFamicom::cpu);
std::destroy_at(&ares::SuperFamicom::bus);
std::destroy_at(&ares::SuperFamicom::cartridgeSlot);
std::destroy_at(&ares::SuperFamicom::controllerPort2);
std::destroy_at(&ares::SuperFamicom::controllerPort1);
std::destroy_at(&ares::SuperFamicom::system);
std::destroy_at(&ares::SuperFamicom::scheduler);
std::destroy_at(&ares::SuperFamicom::random);
std::construct_at(&ares::SuperFamicom::random);
std::construct_at(&ares::SuperFamicom::scheduler);
std::construct_at(&ares::SuperFamicom::system);
std::construct_at(&ares::SuperFamicom::controllerPort1, "Controller Port 1");
std::construct_at(&ares::SuperFamicom::controllerPort2, "Controller Port 2");
std::construct_at(&ares::SuperFamicom::cartridgeSlot, "Cartridge Slot");
std::construct_at(&ares::SuperFamicom::bus);
std::construct_at(&ares::SuperFamicom::cpu);
std::construct_at(&ares::SuperFamicom::smp);
std::construct_at(&ares::SuperFamicom::dsp);
std::construct_at(&ares::SuperFamicom::ppu);
std::construct_at(&ares::SuperFamicom::ppuImpl);
std::construct_at(&ares::SuperFamicom::ppuPerformanceImpl);
std::construct_at(&ares::SuperFamicom::armdsp);
std::construct_at(&ares::SuperFamicom::competition);
std::construct_at(&ares::SuperFamicom::dip);
std::construct_at(&ares::SuperFamicom::epsonrtc);
std::construct_at(&ares::SuperFamicom::hitachidsp);
std::construct_at(&ares::SuperFamicom::icd);
std::construct_at(&ares::SuperFamicom::mcc);
std::construct_at(&ares::SuperFamicom::msu1);
std::construct_at(&ares::SuperFamicom::necdsp);
std::construct_at(&ares::SuperFamicom::obc1);
std::construct_at(&ares::SuperFamicom::sa1);
std::construct_at(&ares::SuperFamicom::sdd1);
std::construct_at(&ares::SuperFamicom::sharprtc);
std::construct_at(&ares::SuperFamicom::spc7110);
std::construct_at(&ares::SuperFamicom::superfx);
std::construct_at(&ares::SuperFamicom::expansionPort, "Expansion Port");
std::construct_at(&ares::SuperFamicom::bsmemorySlot, "BS Memory Slot");
std::construct_at(&ares::SuperFamicom::sufamiturboSlotA, "Sufami Turbo Slot A");
std::construct_at(&ares::SuperFamicom::sufamiturboSlotB, "Sufami Turbo Slot B");
Thread::EntryPoints().clear();
}
